version: "3.3"

services:
  symfony:
    image: kibatic/symfony:7.4
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./:/var/www
    environment:
      SYMFONY_VERSION: 5

  db:
    image: mariadb:10.1.44
    restart: on-failure
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: example
      MYSQL_USER: user
      MYSQL_PASSWORD: user

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - ${ADMINER_PORT-8080}:8080

  node:
    image: node:10
    volumes:
      - ./app:/home/node/app
    working_dir: /home/node/app
    user: ${LOCAL_USER:-1000}

  etherpad:
    image: etherpad/etherpad
    ports:
      - ${ETHERPAD_PORT:-9001}:9001
