version: "3.3"

services:
  nginx:
    restart: unless-stopped
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
      - ./public/:/usr/src/public
      - ./docker/nginx/etherpad.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - etherpad
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  etherpad:
    restart: always
    volumes:
      - ./Etherpad/settings.json:/opt/etherpad-lite/settings.json
    environment:
      ETHERPAD_SSL_PRIVATE_KEY_PATH: ${ETHERPAD_SSL_PRIVATE_KEY_PATH}
      ETHERPAD_SSL_CERT_PATH: ${ETHERPAD_SSL_CERT_PATH}
