version: "3.3"

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        USER_ID: ${LOCAL_USER}
        GROUP_ID: ${LOCAL_USER}
    volumes:
      - .:/usr/src/
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
      - db
    depends_on:
      - db
    user: ${LOCAL_USER}
    working_dir: /usr/src

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./public/:/usr/src/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_PORT}:80

  db:
    image: mariadb:10.1.44
    restart: on-failure
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - ${ADMINER_PORT}:8080

  node:
    image: node:10
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    user: ${LOCAL_USER}

  etherpad:
    build:
      context: https://github.com/ether/etherpad-lite.git#release/1.8.5
      args:
        ETHERPAD_PLUGINS: "ep_align ep_author_hover ep_comments_page ep_copy_paste_images ep_headings2 ep_who_did_what"
    ports:
      - ${ETHERPAD_PORT}:9001
    volumes:
      - ./Etherpad/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
      - ./Etherpad/SESSIONKEY.txt:/opt/etherpad-lite/SESSIONKEY.txt
      - ./Etherpad/patches/GroupManager.js:/opt/etherpad-lite/src/node/db/GroupManager.js
      - ./docker/certbot/conf:/opt/etherpad-lite/letsencrypt
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DB_TYPE: ${ETHERPAD_DATABASE_TYPE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_CHARSET: utf8mb4
      REQUIRE_SESSION: "true"
      ADMIN_PASSWORD: ${ETHERPAD_ADMIN_PASSWORD}

  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8800:8800
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
