version: "3.3"

services:
  php:
    build:
      context: ./docker/php
      args:
        USER_ID: ${LOCAL_USER}
        GROUP_ID: ${LOCAL_USER}
    volumes:
      - .:/usr/src/
    links:
      - db
      - mail
    depends_on:
      - db
    user: ${LOCAL_USER}

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./public/:/usr/src/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php

  db:
    image: mariadb:10.1.44
    restart: on-failure
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - ${ADMINER_PORT}:8080

  node:
    image: node:10
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    user: ${LOCAL_USER}

  etherpad:
    image: etherpad/etherpad
    ports:
      - ${ETHERPAD_PORT}:9001

  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
