version: "3.3"

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        USER_ID: ${LOCAL_USER}
        GROUP_ID: ${LOCAL_USER}
    volumes:
      - .:/usr/src/
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
      - db
      - mail
    depends_on:
      - db
    user: ${LOCAL_USER}
    working_dir: /usr/src

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./public/:/usr/src/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_PORT}:80

  db:
    image: mariadb:10.1.44
    restart: on-failure
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - ${ADMINER_PORT}:8080

  node:
    image: node:10
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    user: ${LOCAL_USER}

  etherpad:
    image: etherpad/etherpad
    ports:
      - ${ETHERPAD_PORT}:9001
    volumes:
      - ./Etherpad/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
      - ./Etherpad/SESSIONKEY.txt:/opt/etherpad-lite/SESSIONKEY.txt
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DB_TYPE: mysql
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_CHARSET: utf8mb4
      REQUIRE_SESSION: "true"
      ADMIN_PASSWORD: "admin"

  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
