version: "3.3"

services:
  nginx:
    restart: unless-stopped
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
      - ./public/:/usr/src/public
      - ./docker/nginx/etherpad.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - etherpad
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  etherpad:
    restart: always
    volumes:
      - ./Etherpad/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
      - ./Etherpad/SESSIONKEY.txt:/opt/etherpad-lite/SESSIONKEY.txt
      - ./Etherpad/patches/GroupManager.js:/opt/etherpad-lite/src/node/db/GroupManager.js
      - ./docker/certbot/conf:/opt/etherpad-lite/letsencrypt
      - ./Etherpad/settings.json:/opt/etherpad-lite/settings.json
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DB_TYPE: ${ETHERPAD_DATABASE_TYPE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_CHARSET: utf8mb4
      REQUIRE_SESSION: "true"
      ADMIN_PASSWORD: ${ETHERPAD_ADMIN_PASSWORD}
      ETHERPAD_SSL_PRIVATE_KEY_PATH: ${ETHERPAD_SSL_PRIVATE_KEY_PATH}
      ETHERPAD_SSL_CERT_PATH: ${ETHERPAD_SSL_CERT_PATH}
    user: 5001:1000
  db:
    restart: always
